name: WAFFah C CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_lint_test:
    runs-on: ubuntu-latest

    steps:
    - name: code checkout (checkout)
      uses: actions/checkout@v3

    - name: install dependencies (gcc, make, clang-tools)
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make clang-format clang-tidy

    - name: format verification (clang-format)
      #Werror to crash if the format is not correct
      #dry-run option to avoid modifying files
      run: clang-format -i --Werror --dry-run src/*.c src/*.h

    - name: static analysis (clang-tidy)
      run: clang-tidy src/*.c -- -I src/

    - name: build project
      run: make

    - name: testing
      run: |
        #start backend in background
        mkdir -p fake_serv && echo "Clean page" > fake_serv/index.html
        cd fake_serv && python3 -m http.server 8080 &
        cd ..
        
        # start the WAF Proxy in background
        ./waffah_bin 8888 127.0.0.1 8080 &
        
        sleep 3
        
        # run the Python test suite
        python3 tests/test_suite.py